services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/application
    volumes:
      - ./application:/var/www/application
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - project

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./application:/var/www/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - project

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-db}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
      MYSQL_USER: ${DB_USERNAME:-username}
    volumes:
      - db_mysql:/var/lib/mysql
    networks:
      - project

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - "8080:80"
    networks:
      - project

networks:
  project:

volumes:
  db_mysql:
